### ISSUE TITLE
Facebook: Data too long for column 'access_token'

### ISSUE THREAD

**Issue by daktech** [ADmad/cakephp-social-auth#30]
G'Day,
I get the following error when using facebook:
Error: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'access_token' at row 1
255 is the max length for BINARY for me so changing access_token to a BLOB fixes it. 
I'm using MYSQL as the DBMS.

**Comment by ADmad** [comment]
Hmm.. In phinx [binary](https://book.cakephp.org/3.0/en/phinx/migrations.html#id2) is DB agnostic and hence I used that. `blob` is MySQL only and I would prefer keeping the migrations file DB agnostic.

**Comment by DevSmartSolutions** [comment]
Same issue on Twitter login.
I'm using MySQL.

**Comment by ADmad** [comment]
@DevSmartSolutions Just change the field type of `acces_token` column.

**Comment by dyske** [comment]
I'd like to report that I came across the same problem. It's not a problem with Google but is a problem with Facebook. The data length of the token exceeds 255, so MySQL stores a truncated version of it. This problem may be hard to catch because it does not cause any problem if you are logging in for the first time because you are not DE-serializing the truncated piece of data at that point. But if you log out and try to log back in using the same account, SerializeType::toPHP will try to deserialize this broken piece of data and you will get an error. So, I would suggest that you change the data type of `access_token` in the migration file to accommodate larger data.

**Comment by robertinosantiago** [comment]
When the access_token column has been changed (e.g. for longtext), the saved content looks like this:

`O:32:&quot;SocialConnect\OAuth2\AccessToken&quot;:3:{s:8:&quot;�*�token&quot;;s:180:&quot;EAADKLd96yFIBADOri3LWM6akzZCLYZB3c7m2wozvabr0RR9UZCjl5INxZADZATejyPaFTfI4c5soLqe6K75FZAgdikJAQyuiGDzmEzEx66ZCyanHTJ8UmYcSDTHUabuZAURFEgEpL7qzs1hWZBoyAtJylSDKSG9FGlv0tBickNKYc3gZDZD&quot;;s:10:&quot;�*�expires&quot;;i:1532262490;s:6:&quot;�*�uid&quot;;N;}`

**Comment by ADmad** [comment]
@robertinosantiago viewing textual representation of this serialized data is pointless. You will get proper data back in php var when it's unseralized (as long as it's not truncated).

**Comment by ADmad** [comment]
@robertinosantiago To confirm you are using type `longtext` for the `access_token` column and things are working fine for you?

If that's the cause I'll just update the migration schema to not use `binary` type for `access_token`.

**Comment by lamasgergo** [comment]
Blob is already good for store this data. but i think it s little bit complicated to read out from this type of field (we need convert i think). but its ok too. better than binary :)
