### ISSUE TITLE
no \ADmad\SocialAuth\Http\Client::class

### ISSUE THREAD

**Issue by dereuromark** [ADmad/cakephp-social-auth#78]
https://github.com/ADmad/cakephp-social-auth/tree/cake-4.x#middleware-config
there is no such class it seems in cake4

I used then `Http\Adapter\Cake\Client` from php-http/cakephp-adapter package which works nicely
Maybe it should be require-dev in your tests
https://github.com/php-http/cakephp-adapter/releases/tag/0.3.0 should work fine
I use the same for Geo plugin

**Comment by ADmad** [comment]
I have updated the readme, that option is no longer required. The custom client class was only required for older version of `SocialConnect/auth` since it has it's own http client interface. Since v3 it uses `Psr\Http\Client\ClientInterface` instance which `Cake\Http\Client` already implements and hence it's directly used.
